In [1]:
from TTS.tts.layers.xtts.tokenizer import VoiceBpeTokenizer

tkz = VoiceBpeTokenizer("hub/vocab.json")

In [2]:
tkz.get_number_tokens()

7544

In [2]:
import json

with open('hub/metadatas.json', 'r') as f:
    metadata = json.load(f)

In [25]:
import torch

embed = torch.nn.Embedding(4, 8)

embed.weight

Parameter containing:
tensor([[-1.5888, -0.0934,  0.1943,  1.0055,  1.0275, -1.5712, -0.1706, -0.5526],
        [ 0.4511,  0.3908, -0.8118, -0.3126,  0.2615, -1.1350,  0.4282, -0.1890],
        [ 0.3736, -0.3715, -0.8391,  0.2562,  0.1873, -1.1685, -1.4860,  0.4564],
        [ 0.7228,  1.4299, -1.3407, -2.9771,  0.3425,  1.4447,  0.7661, -1.0972]],
       requires_grad=True)

In [26]:
trained_weights = torch.load("dummy_embed.pth")
trained_weights

/var/folders/2t/qpkk428j1jdczxdlr9r9sry00000gn/T/ipykernel_26999/585528408.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  trained_weights = torch.load("dummy_embed.pth"

OrderedDict([('weight',
              tensor([[-0.1752, -0.4178,  0.4460, -0.3596,  0.6107, -0.8133, -0.6828, -1.5101],
                      [-1.2445,  1.3214,  0.0788, -1.2455,  0.1225,  1.1557, -1.5495, -0.3115]]))])

In [27]:
embed.load_state_dict(trained_weights)

RuntimeError: Error(s) in loading state_dict for Embedding:
	size mismatch for weight: copying a param with shape torch.Size([2, 8]) from checkpoint, the shape in current model is torch.Size([4, 8]).

In [4]:
embed.weight[:2, :] = trained_weights['weight']

Parameter containing:
tensor([[-1.2869, -0.2954,  0.2266,  0.2110,  0.1858, -0.6695, -1.5153, -0.0889],
        [-0.7938, -1.7776,  1.1101, -1.3797,  1.6609, -0.8274,  0.2735,  0.2021],
        [-0.2661, -1.6203, -0.6736,  1.0769, -0.2879, -0.2187, -0.3808, -1.3017],
        [-0.9004, -0.5890, -0.3541,  0.6662, -0.3859, -0.6739, -0.7375, -0.0116]],
       requires_grad=True)

In [7]:
embed.weight[:2, :] = 0

RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

In [17]:
trained_weights['weight']

<function Tensor.values>

In [22]:
# with torch.no_grad():
embed.weight[:2, :].data = trained_weights['weight'][:2, :].data

In [24]:
embed.padding_idx

In [8]:
import torch
import torch.nn as nn

# Assume we have these dimensions
n = 1000  # number of pretrained embeddings
m = 200   # number of new embeddings to add
d = 300   # embedding dimension

# Pretrained embedding weights (nxd)
pretrained_weights = torch.randn(n, d)

# Create new embedding layer ((n+m)xd)
new_embedding = nn.Embedding(n + m, d)

# Replace first nxd weights with pretrained weights
with torch.no_grad():
    new_embedding.weight[:n, :] = pretrained_weights

# The last m rows remain initialized as they were (typically random)

print(f"Shape of new embedding layer: {new_embedding.weight.shape}")
print(f"First n rows are identical to pretrained weights: {torch.allclose(new_embedding.weight[:n, :], pretrained_weights)}")

Shape of new embedding layer: torch.Size([1200, 300])
First n rows are identical to pretrained weights: True


In [5]:
import torch
import torch.nn as nn

torch.save(nn.Linear(4,8).state_dict(), "dummy_linear.pth")

ln = torch.load("dummy_linear.pth", weights_only=True)

In [10]:
ln['bias']

tensor([ 0.0198, -0.1905,  0.3652, -0.1011, -0.0696,  0.2049,  0.1309,  0.2892])